### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by sarahboyd** [sarahboyd/Text-Analyzer#1]
- [x] add CSV export
- [x] import stop list
- [x] keywords
- [x] update/export stop list
- [x] work on ui
  - [x] word count list
  - [x] help menu
- [ ] fix opening stop list before file problem
- [ ] remove stop words
- [ ] fix exporting empty stop list
